package-lock.json
package.json
scripts/copyBuildFiles.js

Heya @bufferapp/components 👋 ,
Just a quick heads up on the changes here. This PR adds a new script to create a shorter version of the package.json file in the `lib` build directory (where we'll be having our build files) in  order to be able to use shorter imports. So instead of importing the Button by writing `@bufferapp/components/lib/Button`, we can now exclude the `lib` and just type `@bufferapp/components/Button`.
Note that publishing the package has to now be done from the lib folder! I'll add more notes on that to the readme.

Adds a script to support short component imports

---

src/documentation/markdown/Guides/Typography.md

There is a bug on the typography guide where it renders part of a text as HTML. Then, the browser shows a warning on console:
```sh
Warning: validateDOMNesting(...): <head> cannot appear as a child of <p>.
```
And the text is truncated: 
```
You can include the Roboto font, and the needed font weights, directly from the Google Fonts CDN by including the code snippet below between the  tags your app / website:
```
This PR fixes this bug by escaping the HTML tags.

Fix html display on typography guide

---

src/documentation/markdown/Guides/Forms.md

Fix forms guide indentation

---

src/components/Select/Select.jsx

Since using `JSON.stringify` caused issues in items that had a more complex structure, this PR compares the arrays by comparing their length and id, title. If the arrays are the same length and their elements have the same id and title, they are considered equal.
Curious how this feels to you all?
cc @federicoweber @ssvmvss @gomezjuliana

fix comparing select items in getDerivedStateFromProps

---

package.json
src/components/Select/Select.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/components/Select/style.js
src/documentation/examples/Select/SelectWithMenu.jsx

Adds a `marginTop` prop so users can add in a custom margin when they use custom buttons for Selects
I was thinking that this is a needed flexibility so we can use any kinds of buttons. Right now I'm using a customButton for the filter Select in the Reply inbox and I need a smaller margin 😊Happy to hear your thoughts !

adds a custom margin prop to Selects for customButtons

---

package-lock.json
package.json
scripts/sync.sh
src/components/AppShell/__snapshots__/AppShell.spec.js.snap
src/components/Avatar/__snapshots__/Avatar.spec.js.snap
src/components/Button/Button.jsx
src/components/Button/__snapshots__/Button.spec.js.snap
src/components/Input/__snapshots__/Input.spec.js.snap
src/components/NavBar/NavBarMenu/__snapshots__/NavBarMenu.spec.js.snap
src/components/NavBar/__snapshots__/NavBar.spec.js.snap
src/components/Search/Search.jsx
src/components/Search/__snapshots__/Search.spec.js.snap
src/components/Select/Select.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/components/Text/__snapshots__/Text.spec.js.snap

This is useful because styled components >= 4.0 uses `React.forwardRef`, and that is breaking snapshot testing with Jest and Storybook in Analyze. 
This also includes a sync script I was using to temporary clone the build folder in Analyze, we can probably remove that, if we are merging this in.

rollback styled components to v.3.4.10

---

package-lock.json
src/components/Select/SelectItem/style.js

To ensure `SelectItem` elements display their labels with the correct font-family value:

Ensure SelectItem has correct font-family

---

src/components/NavBar/NavBarProducts/NavBarProducts.jsx

This change is needed so users are able to click the product links from the Account app and redirected to the product page.

Change href on product links

---

src/components/NavBar/NavBar.jsx
src/components/NavBar/NavBar.spec.js
src/components/NavBar/NavBarMenu/NavBarMenu.jsx
src/components/NavBar/NavBarMenu/NavBarMenu.spec.js
src/components/NavBar/__snapshots__/NavBar.spec.js.snap
src/documentation/examples/AppShell/AppShell.jsx
src/documentation/examples/AppShell/WithGravatar.jsx

This add adds two default items in the user menu: Account, and Logout, with the following structure:
- logout = `https://login.buffer.com/logout?redirect=https://<product-name>.buffer.com`
- account = `https://account.buffer.com/?product=<product_name>&username=<user.name>`
Passing in any extra `user.menuItems` those will be attached in between the two default items
```
[
account,
...user.menuItems,
logout,
]
```

Add defaults to user menu in AppShell

---

src/components/NavBar/NavBar.jsx
src/components/NavBar/NavBar.spec.js
src/components/NavBar/__snapshots__/NavBar.spec.js.snap
src/documentation/examples/AppShell/WithGravatar.jsx

This can be used by Core, to remove the "Account" button from the user
menu.
To ignore an item just pass it's id in `user.ignoreMenuItems`.

add option to ignore default user menu items

---

src/components/NavBar/NavBar.jsx
src/documentation/examples/AppShell/WithGravatar.jsx

We don't need to show the separator if there aren't any additional menu
items. This is needed for Core Account app.

hide separator if no user.menuItems

---

src/components/Select/style.js

Safari doesn't support the `margin-block-*` properties which was causing some issues with rendering `Select` lists in that browser. I've replaced them with regular margin/padding attributes which resolves the issue.

Fix padding on selects in Safari

---

src/components/AppShell/style.js

Fixes the Height of the AppShell in Firefox

removes the calculated height from the AppShell and adds overflow

---

src/components/AppShell/AppShell.jsx
src/components/AppShell/__snapshots__/AppShell.spec.js.snap
src/components/NavBar/NavBar.jsx

Reply is not able to fully logout, because they rely in localStorage. This new property for the `AppShell` would allow a callback to be passed and executed before the redirect to `/logout` happens
Jira: https://buffer.atlassian.net/browse/REPN-158

AppShell: add onLogout callback to allow apps to cleanup before logout

---

src/components/Avatar/Avatar.jsx
src/components/Avatar/__snapshots__/Avatar.spec.js.snap
src/components/Avatar/style.js
src/documentation/examples/Avatar/Fallback/AvatarWithFallbackImage.jsx

When using the Avatar component, when the image is broken the current approach to handle these scenarios (a mask) isn't always working resulting in something like this:
I added an optional prop to handle those cases and allowing to send a fallback url to the Avatar component which will display in case the actual image fails to load.
- I added a prop in the `Avatar` component
- In the `Avatar` component, I surrounded the `Image` tag with an `Object`, which will load the original image, and the Image will load the fallback in case the first one fails.
I decided to include this change because I am able to see it from Publish and I feel like the user experience should be better, and at least with this change the users won't be seeing broken images.
**Before the change**
**After the change**

Adding fallback url prop

---

src/components/Avatar/Avatar.jsx
src/components/Avatar/__snapshots__/Avatar.spec.js.snap
src/components/Avatar/style.js

Replaced Object tag with a div instead, and added the fallback url in CSS to make the solution lighter.
Using an Object tag just for a fallback image feels a bit unnecessary, so I updated the CSS to make sure the fallback URL works on all browsers (tested in Chrome, Firefox and Safari) and prevent the use of such a heavy tag.
N/A

Replacing Object tag with a div instead

---

src/components/Button/style.js

Certain buttons don't look or read well with everything capitalized:
Example of buttons with all uppercase (current): ❌
Fixed: ✅

Don't capitalize button labels

---

src/components/SidebarListItem/style.js

small tweak to remove the margin-top: 4px from SidebarListItem

removes margin from sidebarlistitem

---

src/components/Select/Select.jsx

I hadn't tested the menu select with the Reply Preferences modal open and when I did, I realized that I introduced a big where now the Select overlaps the Preferences menu. Reverting back to the previous version while I fix this properly :)

returns conditional to close function

---

package-lock.json
src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap
src/components/index.js

Removes the `Sidebar` reference export on `src/components/index.js`, as that file does not exist.
When installing the latest package version (3.12.4) I get a `Module not
found: Error: Can't resolve './Sidebar'` caused by the Sidebar module
still being exported even if it does not exist anymore.

Remove sidebar reference

---

src/components/AppShell/style.js

Allows vertical scroll for AppShell content
Right now we can't scroll down on the Account App, if the window height is smaller than the content, that content is not accessible for the user.
If an app needs to remove vertical scrolling, they can always wrap their content within the AppShell with the `overflow: hidden;` CSS rule and it should work well.

Allow vertical scroll for AppShell content

---

src/components/index.js

Removes CrossSell export from `components/index`.
I'm removing the CrossSell direct export from components/index, as this was breaking tests in Analyze cause of some weird hoisting condition for `styled-components` in nested packages.
Specifically, we noticed this breaking this two PRs:
- https://github.com/bufferapp/buffer-analyze/pull/414
- https://github.com/bufferapp/buffer-analyze/pull/413

remove CrossSell export from components/index

---

src/components/Avatar/Avatar.jsx
src/components/Search/Search.jsx
src/components/Search/__snapshots__/Search.spec.js.snap
src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
src/components/Tooltip/style.js

- Adding zIndex to Tooltip component to remain visible on top of other elements.
- Fixing Avatar and Search props causing warnings in the console.
When adding the Tooltip on the composer in Publish, the Tooltip is being displayed in the back of the composer, by adding the z-index property we can make sure that the Tooltip has the correct visibility.
**Before**
**Now**

Adding zIndex to Tooltip

---

package-lock.json
package.json
src/components/AppShell/__snapshots__/AppShell.spec.js.snap
src/components/Avatar/__snapshots__/Avatar.spec.js.snap
src/components/Banner/__snapshots__/Banner.spec.js.snap
src/components/Button/Button.jsx
src/components/Button/__snapshots__/Button.spec.js.snap
src/components/CrossSell/__snapshots__/CrossSell.spec.js.snap
src/components/Input/__snapshots__/Input.spec.js.snap
src/components/Modal/Modal.jsx
src/components/Modal/__snapshots__/Modal.spec.jsx.snap
src/components/NavBar/NavBarMenu/__snapshots__/NavBarMenu.spec.js.snap
src/components/NavBar/__snapshots__/NavBar.spec.js.snap
src/components/Notification/__snapshots__/Notification.spec.js.snap
src/components/Search/Search.jsx
src/components/Search/__snapshots__/Search.spec.js.snap
src/components/Select/Select.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/components/SidebarHeader/__snapshots__/SidebarHeader.spec.js.snap
src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap
src/components/Text/__snapshots__/Text.spec.js.snap
src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
src/documentation/examples/Modal/focus_reset.jsx
src/documentation/markdown/GettingStarted/Changelog.md

Upgrades Styled components to 4.3.2 💅 
This is a breaking change because innerRef has been deprecated in favor of React.forwardRef.
Also because running multiple versions of styled-components can have unwanted side effects we will need to make sure to upgrade everywhere we want to consume Buffer/ui.
This is part of the effort of keeping our dependencies up to date.

upgrade to styled-components 4.3.2

---

package-lock.json
package.json
src/components/Input/Input.jsx
src/components/Input/InputWithRef.jsx
src/components/Input/index.js

In Reply I needed to pass a `ref` to the input but since we don't have it specified as a prop, it won't allow me. This will let us pass any props to input so we can use it like a native input without having to pass in all the native attributes as props

allows attributes to be passed to input

---

src/components/Modal/Modal.jsx
src/components/Modal/__snapshots__/Modal.spec.jsx.snap
src/documentation/examples/Modal/form-modal.jsx

Adding a new prop to the Modal, to control if the modal is dismissible right after the action in executed.
I'm currently using the BDS Modal component for our Billing in Publish, which contains a form, when hitting on Submit, the modal is being dismissed automatically, and we need to check if the fields are valid before closing the modal, with this change, we can send a "dismissible" prop, and prevent closing it before necessary.
The new dismissible prop is set to true by default, so it doesn't affect the modals that are already in use.

Adding a new "dismissible" prop to the Modal component

---

src/documentation/examples/Select/SelectWithItemsWithNoSelectedState.jsx

Adds a `Select` example in the docs for a Select dropdown where items have no selected state.
We needed a `Select` component in the account application, and creating custom items that had the same styles as the default ones felt too much. This solution felt like it was more maintainable :)
- [] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

Add Select example for a Select dropdown where items have no selected state

---

src/components/Modal/Modal.jsx
src/components/Modal/__snapshots__/Modal.spec.jsx.snap

Currently, the `Modal` component always renders an `action` (button).  This PR proposes a change that only renders the action if one is provided.
With recent PSD2 work on Core, we’ve introduced the [Stripe React Elements library](https://stripe.com/payments/elements) . This library basically builds a Stripe payment flow in React and provides some added Stripe functionality. We’ve found that the cleanest and easiest way to implement these forms is to build them with their own button to easily have access to this functionality. Attempting to use the modal’s (parent) button to submit a child form led to quite a few issues - not to mention having to re-implement this across various repos.

Conditionally render action (button) if provided

---

src/components/Icon/Icon.jsx
src/components/Icon/style.js
src/documentation/examples/Icon/SizeExtraLarge.jsx
src/documentation/examples/Icon/SizeLarge.jsx
src/documentation/examples/Icon/SizeMedium.jsx
src/documentation/examples/Icon/SizeSmall.jsx
src/documentation/markdown/GettingStarted/Changelog.md

Adds an `extraLarge` option to the `size` prop to the `Icon` component to allow for 32x32 icons.
Needing it for designs like [this one](https://cl.ly/946ee1f5d45f), and it also makes sense that we'd have also an Icon with double the size of our `medium` icon.

Add `extraLarge` size option to Icon, to handle 32x32 icons

---

package.json

If the developer does not have the latest component data generated for
the docs, some components might be missing from the documentation after
publishing.
This fixes it by ensuring that any Github pages build triggers that
data generation.
**This won't be a version number upgrade, this is a change done only to our build tools.**

Fix docs generation on npm publish

---

src/components/Select/Select.jsx
src/documentation/markdown/GettingStarted/Changelog.md

passes isOpen state to customButton
This will help is style the open state of the custom button for the shopify top sources component in Analyze

add isOpen param to custom button

---

src/components/SidebarListItem/SidebarListItem.jsx
src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap
src/components/SidebarListItem/style.js
src/documentation/examples/SidebarListItem/SidebarListItemWithIcon.jsx

- Add BadgeIcon, to replace the counter of a SidebarListItem by an icon;
- Add missing `fallbackUrl` prop to the `<Avatar>` on the `SidebarListItem`;
- Change badge proptype to string. 0 is a  falsy value, so passing a number was creating some problems.
[PUB-1567](https://buffer.atlassian.net/browse/PUB-1567)
We are currently implementing the BDS sidebar in Publish. We needed to make a couple of tweaks to address all use cases: 
- we only display the name and not the handle of the profile;
- sometimes we need the  fallbackUrl for the Avatar; 
- we have a couple of situations where the counter is replaced by an icon - in locked and disconnected accounts.

Add badge icon sidebar item

---

src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
src/documentation/examples/Tooltip/option/multiline.jsx
src/documentation/examples/Tooltip/option/withCustomHTML.jsx
src/documentation/examples/Tooltip/option/withHotkey.jsx
src/documentation/markdown/GettingStarted/Changelog.md

Adds a customHTML prop like we have in the Banner component to accept custom HTML in the tooltip
We'd like to use this tooltip in Analyze but want to be able to add in highlights and colour as needed

extend tooltip to accept customHTML

---

src/components/Carousel/Carousel.jsx
src/components/Modal/Modal.jsx
src/components/Modal/__snapshots__/Modal.spec.jsx.snap
src/components/Modal/style.js
src/documentation/examples/Modal/with-carousel.jsx
src/documentation/markdown/GettingStarted/Changelog.md

- adds `customWidth` prop to fit bigger children
- adds `closeCross` prop to add a small cross icon in the top right hand corner (this passes a function that closes the modal from the app)
- adds `noBackground` prop for a floating in mid-air look
- fixes the event listener for the ESC key by adding tabIndex=0 on the Modal so the event registers
We'll need these changes for the modal we're creating in Analyze for Campaigns
- [] I have updated the documentation accordingly.

extending the modal for Analyze Campaigns

---

src/components/NavBar/NavBar.jsx
src/documentation/markdown/GettingStarted/Changelog.md

This PR includes the changes needed allow the NavBar component to re-render if the contents of "products" prop changes.

Allow NavBar to re-render if the contents of "products" prop changes

---

src/components/Modal/Modal.jsx
src/documentation/markdown/GettingStarted/Changelog.md

Links in modal weren't navigating to their respective addresses because of the `e.preventDefault`

fix modal not allowing clicks on links

---

src/components/Select/SelectItem/style.js
src/documentation/markdown/GettingStarted/Changelog.md

When the select item text overflows, the icons are being shrunk down in size due to flexbox. Adding in flex-shrink 0 to ensure they keep their size

add flex-shrink in select for when text overflows

---

src/components/Button/Button.jsx
src/components/Button/__snapshots__/Button.spec.js.snap
src/components/Button/style.js
src/components/Select/Select.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/components/Select/style.js

Adding aria attributes to select dropdown to make it more semantically accurate
Theres a subtle difference as a consequence of these changes, and that is that the split button now has more padding/spacing. You can see the difference in the attached screenshots, its just a few pixels difference. //cc: @letsbleachthis would you mind having a look at the screenshots at all please?
Before:
After:

PUB-2532 | Adding aria attributes to select dropdown to make it more semantically accurate

---

package-lock.json
package.json
src/components/Select/Select.jsx
src/documentation/markdown/GettingStarted/Changelog.md

We noticed that the Select wasn't resetting properly when the search was triggered: https://share.buffer.com/12uy2nye

Allow select to reset even if searching

---

src/components/NavBar/NavBarMenu/NavBarMenu.jsx
src/components/NavBar/NavBarMenu/__snapshots__/NavBarMenu.spec.js.snap

Due to previous changes with the higher level `DropdownMenu` component we no longer need an onClick here.

Remove unused `onClick` prop

---

src/components/NavBar/NavBarProducts/NavBarProducts.jsx

This is a small PR to add a couple of small changes to the `New!` label that's displayed besides product links that are marked as `new`:
- Font size was decreased.
- Border radius was increased.
- A top margin was added to push the label to the bottom a little bit.

Small style tweaks for 'New' label

---

src/components/Button/Button.jsx
src/components/Button/__snapshots__/Button.spec.js.snap
src/components/Button/style.js
src/components/style/colors.js
src/documentation/examples/Button/Type/TypeDanger.jsx

- Adds styles for a button type variation for danger (actions that are destructive)
- Passes down a `danger` prop type to adjust styles
- Passes down a `loading` prop in order to adjust styles based on if the state is loading
- Adds a danger button to the documentation
Adds a danger style variation for buttons that involve a destructive action.
Task from Frontend Board: https://github.com/bufferapp/ui/issues/247
Figma design: https://www.figma.com/file/MgtrTHwQOczkZIhHmxVQ4lEN/BDS-Buttons?node-id=415%3A493
**Active**
**Focus**
**Loading**
- [] I have updated the documentation accordingly.

[UI-247] Add a danger style variation for buttons

---

src/components/Link/Link.jsx
src/components/Link/__snapshots__/Link.spec.js.snap
src/components/Link/style.js
src/documentation/examples/Link/BoldLink.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

To allow `Link` components to have either medium or bold weights. It defaults to medium.
Needed it for [this PR](https://github.com/bufferapp/buffer-account/pull/378), and [this design](https://www.figma.com/file/xOe4E7R2qIHTJYaNjsSAUL/Settings%3A-Channels?node-id=143%3A43).

Add font weight variants to Link component

---

src/components/SimpleModal/SimpleModal.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

adds a z-index so the button always shows on top of the content of the modal

add z-index to simple modal close button

---

src/components/AnimationWrapper/AnimationWrapper.jsx
src/components/AnimationWrapper/AnimationWrapper.spec.js
src/components/AnimationWrapper/__snapshots__/AnimationWrapper.spec.js.snap
src/components/AnimationWrapper/hook.js
src/components/AnimationWrapper/index.js
src/components/Notice/Notice.jsx
src/components/Notice/__snapshots__/Notice.spec.js.snap
src/components/Notification/Notification.jsx
src/components/Notification/__snapshots__/Notification.spec.js.snap
src/components/SimpleModal/SimpleModal.jsx
src/components/SimpleModal/__snapshots__/SimpleModal.spec.js.snap
src/components/index.js
src/components/style/animations.js
src/documentation/examples/AnimationWrapper/AnimationWrapper.jsx
src/documentation/examples/AnimationWrapper/AnimationWrapperHook.jsx
src/documentation/examples/SimpleModal/SimpleModal.jsx

Add the `AnimationWrapper` component to handle stage-in and stage-out animations on content change.
This can be used as a simple wrapper around rendering components to smoothly animate the transition between content states, for example, it is used in the `SimplaModal` to show a card change animation when re-rendering the card content.
- runs the `stage-in` animation on initial rendering
- on children changes it
1. detects the content change
2. pause the DOM mutation
3. runs the stage-out animation
4. apply DOM changes (re-render)
5.  and finally runs the `stage-in` animation.
- on dismiss it:
1. runs the `stage-out` animation
3. stop rendering the children 
2. run the `onDismiss` callback 
Small transitional animations enhance the user experience and give the feeling of a more polished …

Add AnimationWrapper component

---

src/components/SegmentedControl/Option/style.js
src/components/SegmentedControl/style.js
src/documentation/markdown/GettingStarted/CHANGELOG.md

Discrepancies were found in Segmented Control sizes. The designs use inner border instead of adding a px to the outside. There is also a border around the options set to transparent that is given color when in a focus state. The borders around the two components collectively added a total of 4px extra to the height. This PR reduces the parent component and option component padding to compensate for the borders.

Fix Segmented Control padding

---

src/components/Tag/style.js
src/documentation/markdown/GettingStarted/CHANGELOG.md

Fix the color of the text inside `Tag` component when it's used in a hoverable element.
_Not hovered_:
_Hovered:_

fix: Tag hover text color

---

src/components/DropdownMenu/ButtonItem/ButtonItem.jsx
src/documentation/examples/DropdownMenu/DropdownMenu.jsx

This PR adds a new property `tag` to the MenuItem in the Dropdown Menu component. It replicates the idea of the `icon` property.
The motivation behind is to remove the warning
> checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `item.title` of type `object` supplied to `ButtonItem`, expected `string`.
when passing an object instead of a string.

Add tag property to MenuItem in DropdownMenu

---

src/components/Select/Select.jsx
src/components/Select/Select.test.js
src/documentation/examples/Select/SelectWithSelectAll.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

- Only set `isFiltering` to `true` if `searchValue` has a value 
- Set `selectedItems` state to `items` prop in `getDerivedStateFromProps`
- Update `searchFiled` typo to `searchField`
- Add example of a Select with a Select All option
- Add test to ensure `isFiltering` state is being set correctly
The `Select` component implements the `Search` component with `clearSearchOnBlur` set to `true`. Because the `Search` field is auto focused, the first click after opening the `Select` menu always runs the `Search` component's `onBlur` callback, which, in this case, is the `onSearchChange` method.
The `onSearchChange` method always sets `isFiltering` to `true`, even if the provided `searchValue` is an empty string, which is always the case when the `Search` field is being blurred because of the …

[PUB-3784] Fix/search field breaks multi select

---

src/components/Search/Search.jsx
src/components/Search/__snapshots__/Search.spec.js.snap
src/components/Select/Select.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

Revert a prop name that was renamed as changing an existing prop name is technically a breaking change

[PUB-3576] Revert renamed Search prop name

---

src/components/Select/Select.jsx
src/components/Select/Select.test.js
src/components/Select/__snapshots__/Select.spec.js.snap
src/documentation/markdown/GettingStarted/CHANGELOG.md

Add the ability to specify a `hideOnSearch` property on items being passed to the Select component. If this value is set to true, the item will never be displayed as an available option during search.
Fix for ticket [PUB-3845](https://buffer.atlassian.net/browse/PUB-3845?atlOrigin=eyJpIjoiZTQ4ZDIxMzU3NTU3NDRkMzk1ODU3NDAyZWQxNzliMDQiLCJwIjoiaiJ9)
We need a "Select all" option for Calendar's Channel filter feature. 
This option should either always show at the top of the list while searching, regardless of the search value, or never show during search.
The simplest solution that also makes sense practically is to never show it while searching. The assumption is that users are searching for a specific channel and will usually not want to select all channels while in this state.

[PUB-3845] Add ability to hide specific items during search in Select component

---

package.json
src/documentation/markdown/GettingStarted/CHANGELOG.md

We had added displayNames to try avoiding class collisions between SP and the Navigator. [After the investigation](https://threads.com/34407290541), we noticed it's unnecessary and adds weight to be bundle. I also added back in minification as it was included in earlier versions.

remove displayName from babel config

---

src/components/Select/SelectItem/SelectItem.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/documentation/examples/Select/SelectWithItemTooltip.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

- if a `tooltip` property is passed as part of a Select item, the value will be rendered in a Tooltip on hover instead of the item `title`.
We need to render a tooltip for a specific select item to provide additional context around selecting the item.

Add the ability to pass a tooltip along with a Select item

---

src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
src/documentation/examples/Tooltip/visibility/notVisible.jsx
src/documentation/examples/Tooltip/visibility/visible.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

- only render tooltip component if a `label` or `customLabel` is provided
- add visibility examples for visible tooltip and not visible tooltip
Because the tooltip is a wrapper, when a component conditionally needs a tooltip it's always a hassle to conditionally wrap it. This change allows you to only render the tooltip component if a label is provided.

Only render tooltip if a label is provided

---

src/components/Button/Button.jsx
src/components/Button/style.js
src/components/Select/Select.jsx
src/components/Select/__snapshots__/Select.spec.js.snap
src/documentation/examples/Button/Type/TypeSplitSmall.jsx

The `size` property was not being used on split buttons. Sofia noticed it in the Queue view in the webapp, and thought I would fix it here.
Before:
After:

fix: respect size setting on split Button

---

src/components/Avatar/Avatar.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

Fixing proptypes in Avatar.jsx - they were missing `googlebusiness` value

Fixing Avatar.jsx proptypes

---

src/components/Input/Input.jsx
src/components/Input/__snapshots__/Input.spec.js.snap
src/components/Input/style.js
src/documentation/examples/Input/option/WithIcon.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

As in the title. Use an Icon component inside the Input, in the same way you can use a prefix text.

Support Icon for Input

---

package.json
src/components/Notice/Notice.jsx
src/components/Notice/__snapshots__/Notice.spec.js.snap
src/documentation/examples/Notice/NoticeDismissableNoAnimation.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

If you set `disableAnimation` to the `Notice` component, you cannot dismiss the notice because it relies on the `AnimationWrapper` to hide the Notice. This PR removes the animation properties before sharing them to the `AnimationWrapper`.
We are using the Notice component to create a banner in Mastodon Profile pages to encourage customers to follow Buffer.

Fix Notice Dismiss

---

package.json
src/components/Tooltip/style.js
yarn.lock

Initial PR with context: bufferapp/ui#429
Hey @esclapes @ssvmvss @gmzjuliana @MayaUribe, I would love your help with this change. All the tests pass, but when it comes to publishing (when node scripts/build.js runs), I get the following error:
```
./node_modules/@reach/tooltip/dist/reach-tooltip.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```
This is the changelog for version 0.18.0 - https://github.com/reach/reach-ui/blob/main/packages/tooltip/CHANGELOG.md
Any clue what may be going on here? I'm a bit out of my depth. I did some Google search, and tried to use a full path using `/dist` as shared [here](https://github.com/framer/motion/issues/1525), but it didn't improve.

Revert "Revert "Update reach/tooltip to latest""

---

package.json
yarn.lock

Finally, using reach/tooltip@0.13.0 because of an error in their tagging, and 0.12.1 was still required react < 17.
Related to: https://github.com/bufferapp/ui/pull/432

Using reach/tooltip@0.13.0 

---

src/documentation/examples/Button/Type/TypePrimaryIcon.jsx
src/documentation/examples/Button/Type/TypePrimaryIconEnd.jsx
src/documentation/markdown/GettingStarted/CHANGELOG.md

We've added new message icons so we need to replace these in the Button examples so the page doesn't break

replace outdated Message icon with new icon
