package.json, scripts/publish.sh
Hey @ivanaszuber I took the liberty to add in a small script to run all the necessary steps to publish an updated version to NPM :smile:.
We can run it with `npm run publish [<newversion> | major | minor | patch]`
=> add publish script

package-lock.json, package.json, scripts/publish.sh
=> Fix publish script

src/components/Button/style.js
Same as #16 but takes into account the changes in #15 😁
=> expands the clickable area of the isSplit select button

package.json
This should fix the bug @anafilipadealmeida was seeing:
https://github.com/bufferapp/buffer-publish/pull/507#issuecomment-454796244
=> Move `immutability-helper` into regular deps

.eslintrc.json, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Select/Select.jsx, src/components/Select/__snapshots__/Select.spec.js.snap
- adds the `isOpen` prop to the `Select` component in order to be able to open the selects from the apps using the component
=> adds isOpen prop to the Select component

package.json, src/documentation/app/AppContainer.jsx, src/documentation/app/layout/navbar/NavBar.jsx
http://hi.buffer.com/6f21d62fe91b
=> adds package version to docs site

src/components/Button/Button.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Select/Select.jsx, src/components/Select/__snapshots__/Select.spec.js.snap, src/components/Select/style.js, src/documentation/examples/Select/SelectIconOnly.jsx
I've got one little bug on this one! The way we're using overflow means that in the doc site, the dropdown gets covered by the sidebar... something similar happened in Reply but we were able to move the overflow, here I wasn't able to find a good solution (yet! hahaha anyone have any ideas?)
http://hi.buffer.com/e424f9b5d705
=> adds iconOnly select

src/components/AppShell/AppShell.jsx, src/components/AppShell/__snapshots__/AppShell.spec.js.snap
- fixes merge conflict with master branch (this change was already pushed to master in a previous branch)
=> fix merge conflict

src/components/Modal/Modal.jsx, src/components/Modal/Modal.spec.jsx, src/components/Modal/Modal.test.js, src/components/Modal/__snapshots__/Modal.spec.jsx.snap, src/components/Modal/index.js, src/components/Modal/style.js, src/components/index.js, src/documentation/examples/Modal/basic-modal.jsx, src/documentation/examples/Modal/focus_reset.jsx, src/documentation/examples/Modal/wide-modal.jsx, src/documentation/examples/Modal/with-background.jsx
To add a generic Modal component
=> add Modal component

src/components/Modal/Modal.jsx, src/components/Modal/__snapshots__/Modal.spec.jsx.snap, src/documentation/examples/Modal/basic-modal.jsx
To disable individual action buttons on `Modal`.
=> add option to disable buttons in Modal

src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Select/Select.jsx, src/components/Select/Select.test.js, src/components/Select/__snapshots__/Select.spec.js.snap
Ensures the Select can be closed by clicking on `SelectButton`.
=> fix Select toggle on button click

README.md
Hi! :wave:  
I found this little issue while investigating the repo
=> [FIX]: fixes link to documentation

package-lock.json, src/components/Input/Input.jsx, src/components/Input/__snapshots__/Input.spec.js.snap, src/documentation/examples/Input/option/WithOnBlur.jsx
Adding onBlur option to Input fields.
=> Adding onBlur option for Input.

src/components/NavBar/NavBar.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap
This will make sure that menuItems.component propType lines up with SelectItem.component propType
=> change propType for menuItems component to func

package-lock.json, package.json, src/components/AppShell/AppShell.jsx, src/components/NavBar/NavBar.jsx, src/components/NavBar/NavBarMenu/NavBarMenu.jsx, src/components/NavBar/NavBarMenu/__snapshots__/NavBarMenu.spec.js.snap, src/documentation/examples/AppShell/WithGravatar.jsx
To use Gravatar when we are not providing an avatar image url in the user object.
It will default to a custom one if the user doesn't have a Gravatar.
=> add gravatar to AppShell

src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Search/Search.jsx, src/components/Search/__snapshots__/Search.spec.js.snap, src/components/Search/style.js, src/components/Select/Select.jsx, src/components/Select/SelectItem/SelectItem.jsx, src/components/Select/SelectItem/style.js, src/components/Select/__snapshots__/Select.spec.js.snap, src/documentation/examples/Select/SelectWithInputSearch.jsx, src/documentation/examples/Select/SelectWithoutCapitalize.jsx
Adding new props for Select and Search components.
=> Adding new props for Select and Search components.

src/components/Banner/__snapshots__/Banner.spec.js.snap, src/components/Search/Search.jsx, src/components/Search/__snapshots__/Search.spec.js.snap
Adding clearSearchOnBlur option to clear search field when enabled.
=> Adding clearSearchOnBlur prop to Search component

src/components/NavBar/NavBar.jsx
Fex logout url passing `baseUrl` to `getLogoutUrl` 😞
=> fix logout url

src/components/NavBar/NavBar.jsx, src/components/NavBar/NavBar.spec.js
To provide the full redirect url to Account.
=> replace product with redirect query param for account

package-lock.json, package.json, src/components/NavBar/NavBar.jsx, src/components/NavBar/NavBarMenu/NavBarMenu.jsx, src/components/NavBar/NavBarMenu/NavBarMenu.spec.js, src/components/NavBar/NavBarMenu/__snapshots__/NavBarMenu.spec.js.snap, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/documentation/examples/AppShell/WithDefaultAvatar.jsx
* No Gravatars as per @twanlass's suggestion, we'll go straight the default avatar for now instead (unless you pass one in.)
* Don't force title case on menu items in the AppShell's NavBar.
=> [AppShell] Remove Gravatar support and also no title case in menus

src/components/NavBar/NavBarProducts/NavBarProducts.jsx
- Adds `font-weight` property to product-text element in navbar component
=> Specifies font-weight for product text element.

src/components/NavBar/NavBar.jsx
This force the NavBar to use pass the correct username to the /account url.
Solve a bug where we were passing undefined or '...' to the account app.
=> fix username param in account url

package-lock.json, src/components/NavBar/NavBarMenu/style.js
- Ensure long names, emails don't extend beyond a certain width pushing other menu items out of the way (`text-overflow: ellipses`
- Customers with long names or emails will see the navbar layout break or wrap poorly
=> Ensure long names / emails are ellipsed, don't overflow

src/components/SidebarListItem/style.js
I forgot to put back the margins! Sorry 🙈
=> fix margin-top exaggeration

src/components/Select/Select.jsx
If a customButton select is open and a user clicks on a customButton (like NavBarMenu) again, the select will close.
ref: https://buffer.atlassian.net/browse/BC-75
=> close custom buttons on click

src/components/NavBar/NavBar.jsx, src/components/NavBar/NavBarMenu/style.js, src/components/NavBar/NavBarProducts/NavBarProducts.jsx
Minor polish items for NavBar component
- Fixes Publish icon colors (order was swapped before)
- Fixes z-index issue with vertical rule elements 
- Optically adjusts size of Analyze icon (larger) 
- Visual polish
=> Minor visual polish for NavBar component.

src/components/Button/style.js
- Adjusts hover state styles for primary button to match Figma designs (adjusts background and border color). 
- small bit of visual polish
=> Updates primary button styles to match BDS.

src/components/NavBar/NavBar.jsx
- Minor visual polish for the navbar component to add contrast to bottom border
=> Update navbar border color for better contrast.

src/components/SidebarListItem/SidebarListItem.jsx, src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap, src/components/SidebarListItem/style.js, src/documentation/examples/SidebarListItem/SidebarListItem.jsx
Sets the icon colour inside of bufferui
Added a hover state to the icons accompanying the SidebarListItem for visual niceness
http://hi.buffer.com/dc2f21a3535e
=> add hover to SidebarListItem icon

src/components/SidebarListItem/style.js
changes icon to white when selected and renames colour variables instead of hex codes
=> few style fixes

src/components/CrossSell/style.js
This PR was created to:
- Allow scroll only on y axis.
- Increase top margin on sub-header.
=> Add improvements to the CrossSell component

src/components/CrossSell/style.js
This PR was created to add some bottom margin on CrossSell's footer for smaller screens.
=> Add margin-bottom on CrossSell's footer for smaller screens

src/components/NavBar/NavBar.jsx
The NavBar was being updated only if the username changed. This was causing a problem to the Account application since the email is loaded asynchronously there.
=> Allow NavBar to be updated if email changes

package-lock.json, src/components/AppShell/AppShell.jsx, src/components/AppShell/__snapshots__/AppShell.spec.js.snap, src/components/Banner/Banner.jsx, src/components/Banner/__snapshots__/Banner.spec.js.snap, src/components/Banner/style.js, src/components/Select/Select.jsx, src/components/style/colors.js, src/documentation/examples/AppShell/WithBanner.jsx, src/documentation/examples/Banner/BannerWithHtml.jsx
* Add a new theme prop to the Banner to support the 'orange' color 🎨 
* Use the new darker blue for the Banner (see [Figma](https://www.figma.com/file/LL6ymcR49hfNW3KWFMLtU3Xp/BDS-Banner?node-id=0%3A1))
* Fix the AppShell not passing `customHTML` to it's Banner ✅ 
Just some incremental improvements and bugfixes!
=> Banner Improvements ✨

package-lock.json, src/components/NavBar/NavBarProducts/NavBarProducts.jsx
- Fixes Reply active state in navbar – icon colors now match brand (blue and orange were swapped)
=> Fixes Reply active icon state in navbar.

package-lock.json, package.json
Upgraded React version to the latest -> 16.8.6
Upgrading to the latest version would help us use some of the newest React features and external libraries.
=> Upgrading React version to 16.8.6

package-lock.json, package.json, src/components/Tooltip/Tooltip.jsx, src/components/Tooltip/Tooltip.spec.js, src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap, src/components/Tooltip/index.js, src/components/Tooltip/style.js, src/components/index.js, src/components/style/fonts.js, src/documentation/examples/Tooltip/option/multiline.jsx, src/documentation/examples/Tooltip/option/withHotkey.jsx, src/documentation/examples/Tooltip/position/bottom.jsx, src/documentation/examples/Tooltip/position/left.jsx, src/documentation/examples/Tooltip/position/right.jsx, src/documentation/examples/Tooltip/position/top.jsx, src/index.jsx
Adding new Tooltip component to maintain consistency in our products.
We are currently using Tooltip throughout all our applications that aren't consistent, which is why we feel the need to add a Tooltip component that will be useful in all of our apps.
=> [BC-74]  Creating Tooltip component with reach-ui library.

src/components/Tooltip/Tooltip.jsx
Adding validation around tooltipWrapper, to make sure is not null before getting the children.
We are getting a snapshot error from Publish when using the Tooltip saying that `tooltipWrapper` is null, which is why I added the check before fetching its children.
=> Tooltip ref validation on componentDidMount

src/components/SocialButton/SocialButton.jsx, src/components/SocialButton/SocialButton.spec.js, src/components/SocialButton/__snapshots__/SocialButton.spec.js.snap, src/components/SocialButton/index.js, src/components/SocialButton/style.js, src/components/index.js, src/components/style/colors.js, src/documentation/examples/SocialButton/FacebookSocialButton.jsx, src/documentation/examples/SocialButton/InstagramSocialButton.jsx, src/documentation/examples/SocialButton/LinkedinSocialButton.jsx, src/documentation/examples/SocialButton/PinterestSocialButton.jsx, src/documentation/examples/SocialButton/TwitterSocialButton.jsx, src/documentation/markdown/GettingStarted/Changelog.md, src/documentation/markdown/UI.md
Add SocialButton Component to BDS.
Both Reply and Publish use/ will use buttons to connect a social account (Facebook, Instagram and Twitter)
[BC-95](https://buffer.atlassian.net/browse/BC-95)
=> Add SocialButton component

src/components/Banner/Banner.jsx, src/components/Button/Button.jsx, src/components/Button/style.js, src/documentation/examples/Banner/BannerOrange.jsx, src/documentation/examples/Button/Type/TypeOrange.jsx
To fix the color of the button on the orange banner
We are currently using the blue primary button on the orange background, the button should be dark orange.
=> fix button on orange banners

src/components/Button/Button.jsx, src/documentation/examples/Button/Type/TypeSplitButtonWithCustomSelect.jsx, src/documentation/markdown/GettingStarted/Changelog.md
I'm implementing the ability to not use the standard select component for split buttons, but instead use a custom react component in its place. This will allow us to customize the contents of the split menu, but not break existing code.
The UI in publish I'm using this for is already in place, and just needs to upgrade the button to support split buttons without checking the option in the split button. To do this I've allowed the user to add a child component to the split button.
```
import React from 'react';
import Button from '@bufferapp/ui/Button';
import UISelect from '@bufferapp/ui/Select';
class Select extends UISelect {
handleSelectOption = (option, event) => {
this.props.onSelectClick(option, event)
this.setState({
isOpen: false,
})
}
}
/** Split Button With Custom Select */ …
```
=> Adding custom split button child select element

CONTRIBUTING.md, scripts/publish.sh
Adding publish command to docs and adding the push tags command for git so releases are tagged in github too
=> Updating publish command to push tags and to add publish command to contributing docs

package.json, scripts/betaPublish.js
To have a handy way to generate new beta versions without having to go through the whole process manually, allowing people to test their changes within their apps in staging without having to merge and deploy the changes as a final version.
Whenever you want to deploy a new beta version, just running `npm run publish-beta` will take care of it and will return back to you the newly generated version number.
I am looking forward to reducing friction for engineers to work more on this repo by default when building new components.
=> "beta:publish" script

src/documentation/markdown/GettingStarted/Changelog.md
=> update changelog with 5.10 and 5.11

package-lock.json, scripts/betaPublish.js, scripts/generateIconComponents.js, src/components/AppShell/AppShell.jsx, src/components/AppShell/__snapshots__/AppShell.spec.js.snap, src/components/Input/Input.jsx, src/components/Input/__snapshots__/Input.spec.js.snap, src/components/Input/style.js, src/components/NavBar/NavBar.spec.js, src/components/SidebarListItem/SidebarListItem.jsx, src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap, src/documentation/examples/Input/option/WithPrefix.jsx, src/documentation/markdown/GettingStarted/Changelog.md
In order to support the designs for the User Tagging feature in Publish, I've added the ability to pass along a prop that defines the text and necessary spacing in the input field.
For User Tagging in Publish. See https://buffer.atlassian.net/browse/PUB-2127
=> Add fixed text 'prefix' prop to `Input` component

src/components/Input/Input.jsx, src/components/Input/__snapshots__/Input.spec.js.snap, src/components/Input/style.js, src/documentation/examples/Input/option/WithPrefix.jsx, src/documentation/markdown/GettingStarted/Changelog.md
=> hotfix label with prefix on input component

src/documentation/markdown/GettingStarted/Changelog.md
Update the changelog to reflect changes from the latest versions 5.13.0 - 5.17.0
=> Update changelog following dollar icon publish (5.13.0)

src/components/Select/Select.jsx, src/documentation/markdown/GettingStarted/Changelog.md
Adds disabled and selected as fields for comparison so that if they change, the items change accordingly
I noticed while working in Analyze, that if the `selected` and `disabled` fields in items change, the select options aren't rerendering properly
Without the rerendering: https://share.buffer.com/8LuZYm6r
with the change: https://share.buffer.com/Z4uzGegY
=> adds conditions for selected and disabled for rerendering

src/documentation/examples/Modal/basic-modal.jsx, src/documentation/examples/Modal/focus_reset.jsx, src/documentation/examples/Modal/form-modal.jsx, src/documentation/examples/Modal/wide-modal.jsx, src/documentation/examples/Modal/with-background.jsx
Just fixing the docs for the modal, adding some React hooks to manage the state on every example for opening and closing them.
=> Fix modal docs

src/components/Select/style.js
a minor change to ensure the margin persists across browsers
=> swap margin and padding to fix across chrome, firefox and safari

package-lock.json, package.json, src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap, src/components/Tooltip/style.js, src/documentation/markdown/GettingStarted/Changelog.md
Updating Tooltip styles.
In Publish the Tooltip stopped working, and adding the position absolute fixes it.
=> Adding position absolute to tooltip.

src/components/Tooltip/Tooltip.jsx, src/documentation/examples/Tooltip/option/withCustomLabel.jsx, src/documentation/markdown/GettingStarted/Changelog.md
rename customHTML prop to customLabel for dev clarity
=> rename customHTML to customLabel

src/documentation/markdown/GettingStarted/Changelog.md
=> Update changelog to 5.25.0

src/components/AppShell/style.js, src/components/Banner/style.js, src/components/CrossSell/style.js, src/components/Input/style.js, src/components/Notification/style.js, src/components/Select/style.js, src/components/SidebarHeader/style.js, src/components/Text/Text.jsx, src/components/style/colors.js
- Fix BDS colors (`red`, `blueLighter`, `green` and `redLight` didn't fully match the documentation)
- Add `pinkLighter`, `blueLight` and `redDark` to the list of colors
- Add possibility to create Text `blue` and `grayDark`
- Replace color codes across the components by the color variable
=> Fix BDS colors

src/documentation/examples/Carousel/Carousel.jsx, src/documentation/examples/Modal/with-carousel.jsx
I originally had some placekittens https://placekitten.com/ in for the images but substituted them for a more on-brand placeholder
=> add nicer images to exmaples

src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Select/Select.jsx, src/components/Select/Select.test.js, src/components/Select/__snapshots__/Select.spec.js.snap, src/documentation/examples/Select/SelectWithCustomItem.jsx, src/documentation/examples/Select/SelectWithMenu.jsx, src/documentation/examples/Select/SelectWithMenuAndCustomItem.jsx
Removing condition to enable closing popup for custom button on Select component.
In Publish we are working on Campaigns project and we need to use the Select component with a CustomButton, however, there's a bug currently in which the toggle visibility doesn't work.
This change impacts on Reply menu, context for Slack conversation [here](https://buffer.slack.com/archives/CE4NLGLR5/p1584638528064100).
=> Close popup for custom button on Select component

src/components/NavBar/NavBar.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/components/Select/Select.jsx, src/components/Select/SelectItem/SelectItem.jsx, src/components/Select/__snapshots__/Select.spec.js.snap, src/documentation/examples/AppShell/AppShell.jsx
Fix for the AppShell Select component not closing when selecting an option.
After the last fix version (5.30.0) I saw the AppShell error I think @juliana mentioned before, and I decided to create a new PR to fix that one instead of reverting, more context:
- AppShell bug after Select fix 5.30.0 [[REF](https://share.buffer.com/eDuxKmKN)] (Menu won’t close when selecting an option)
- AppShell with the new fix [[REF](https://share.buffer.com/jkuKpzj0)]
- AppShell bug after Select fix 5.30.0 [[REF](https://share.buffer.com/eDuxKmKN)]
- AppShell with the new fix [[REF](https://share.buffer.com/jkuKpzj0)]
=> Fix for AppShell menu not closing when selecting option

src/components/NavBar/NavBar.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/documentation/examples/AppShell/AppShell.jsx
Fixes bug for clicking on help items, is currently not clicking.
Slack conversation [here](https://buffer.slack.com/archives/CHN88PG2J/p1585351654016000)
With the latest changes to the Select component, the help menu started failing to click.
=> Handling click event in NavBar for help items.

src/components/Modal/style.js
makes the modal background overlay slightly darker
[[Current Ref](https://share.buffer.com/yAuvE61J)][Darker background with 0.7 opacity](https://share.buffer.com/WnuNgBmg)
=> makes the modal background overlay darker

src/components/Modal/style.js, src/documentation/markdown/GettingStarted/Changelog.md
=> updates changelog

src/components/Modal/style.js, src/documentation/markdown/GettingStarted/Changelog.md
This is a very, very small change 🙈
=> move close button closer to modal

src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/documentation/markdown/GettingStarted/Changelog.md
This is a small PR to:
- Update the changelog with version 5.34.0 and 5.34.1.
- Update snapshots.
=> Update changelog with version 5.34.0 + Tests

src/components/Carousel/Carousel.jsx, src/components/Modal/style.js, src/components/style/animations.js, src/documentation/examples/Modal/with-carousel.jsx
To add some small animations to Modal and carousel
We are using the modal with a carousel/card in it all over Analyze, and to make it a bit smoother I've added in some small animations 💅.
=> add modal and carousel animations

src/components/AppShell/AppShell.jsx, src/components/AppShell/__snapshots__/AppShell.spec.js.snap, src/components/NavBar/NavBar.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/documentation/examples/AppShell/AppShell.jsx, src/documentation/markdown/GettingStarted/Changelog.md
A skip to main content link appears when a user is on a screen reader and the link is in focus. To work properly, each page will need to have an element with the id main (ex. `<main id="main"></main>`)
This feature is optional, as the default prop will be set to false
I first learned about this feature when I was looking into [WCAG Level A requirements](https://www.w3.org/TR/WCAG20/#navigation-mechanisms-skip) for VPAT.
This change will make is easier for users to get to the main content on a page. For example, within publish, a user would need to get through the nav and in most cases profile sidebar & tab before they could get to the main content. There are shortcuts (navigate with headings) though not all screen readers support this.  
I'm keen to hear any thoughts around this change :) …
=> Add an optional skip to main content link to the nav bar

.travis.yml, package-lock.json, src/components/Input/Input.jsx, src/components/Input/__snapshots__/Input.spec.js.snap
Add id in Input field to match the htmlFor from label for accessibility reasons.
Just noticed this one while testing a form that uses an Input.
Jira card -> [PUB-2243](https://buffer.atlassian.net/browse/PUB-2243)
=> PUB-2243 | Add id for Input field to match the htmlFor from label

package-lock.json, package.json, src/components/Select/SelectItem/SelectItem.jsx, src/components/Select/SelectItem/style.js, src/documentation/markdown/GettingStarted/Changelog.md
When we first made the Select element, I arbitrarily reused the container we were using for the check mark that is shown when an item is selected. Now, I hope we can expand this to have more flexibility with the custom icons we use in the dropdown list as we need this for the analyze profile selector
There is one little thing and it's that I'd love to know if this breaks your styles, as I've seen a very slight difference in the custom icons in our documentation: https://share.buffer.com/8LujE2bR
=> add flexibility for height and width in custom icons for Select

src/documentation/markdown/GettingStarted/Changelog.md
=> bump changelog version number

src/components/SidebarListItem/SidebarListItem.jsx, src/documentation/examples/SidebarListItem/SidebarListItemWithCustomBadge.jsx
Small one to fix warnings in Publish (since we're passing a Node).
=> Allow node for `badges` in `SidebaListItem`

src/components/NavBar/NavBar.jsx, src/documentation/examples/AppShell/WithOrgSwitcher.jsx
=> Add LinkedIn Icon support to Org Switcher popout

src/components/DropdownMenu/PopupMenu/PopupMenu.jsx, src/components/DropdownMenu/TooltipLabel/TooltipLabel.jsx, src/components/NavBar/NavBar.jsx, src/components/NavBar/__snapshots__/NavBar.spec.js.snap, src/documentation/examples/AppShell/WithOrgSwitcher.jsx
Tweak org switcher styles according to updated Figma file
- Styling adjustment when there is only one social network in the Tooltip
- Add default message when no networks in an org
=> PUB-2882  | Update org switcher styles

src/documentation/markdown/GettingStarted/Changelog.md
Updates the changelog with 5.43.0 details.
=> Update Changelog with 5.43.0 changes

package-lock.json, src/components/Switch/Switch.jsx, src/components/Switch/Switch.spec.js, src/components/Switch/__snapshots__/Switch.spec.js.snap, src/components/Switch/index.js, src/components/Switch/style.js, src/components/index.js, src/documentation/examples/Switch/Switch.jsx, src/documentation/examples/Switch/SwitchDisabled.jsx, src/documentation/examples/Switch/SwitchOff.jsx, src/documentation/examples/Switch/SwitchOn.jsx, src/documentation/markdown/GettingStarted/Changelog.md
Add a switch component related to this [Publish jira task.](https://buffer.atlassian.net/browse/PUB-2829) 
I decided to name it Switch instead of Toggle, as [toggling a button](https://material.io/components/buttons#toggle-button) can mean more than one thing. 
I checked out accessible examples from [Chakra](https://chakra-ui.com/switch) and [Dev.io](https://dev.to/link2twenty/accessibility-first-toggle-switches-3obj). 
Screenshot: https://share.buffer.com/geuwnPXD
Focus state: https://share.buffer.com/X6uomnl7
Disabled state: (has `cursor: not-allowed`): https://share.buffer.com/mXuAwvP4
=> [PUB-2829] Add switch component

src/components/DropdownMenu/PopupMenu/style.js, src/documentation/markdown/GettingStarted/Changelog.md
- Adjust max-height and scroll of PopupMenu
_Created a beta version 5.44.0-beta.e104eee to test it in Publish_ 🙂 
https://buffer.atlassian.net/browse/PUB-2916
With the org switcher, users with many orgs were having some issues with scrolling: https://share.buffer.com/bLujN9XO as the content is taller than the page. This fix works considering that we use the dropdown menu with the appshell navbar. If in the future there's another use of the dropdown menu that requires an adjustment of the max-height, we should consider transforming this into a prop.
=> [PUB-2916] Adjust max-height PopupMenu

src/components/Notice/Notice.jsx, src/components/Notice/Notice.spec.js, src/components/Notice/__snapshots__/Notice.spec.js.snap, src/components/Notice/index.js, src/components/index.js, src/documentation/examples/Notice/Notice.jsx, src/documentation/examples/Notice/NoticeDismissable.jsx, src/documentation/examples/Notice/NoticeLongText.jsx, src/documentation/examples/Notice/NoticeWarning.jsx
Adds Notice component, just warning for now:
We'll need this in Analyze and Account for Boosted Post Insights
=> adds Notice component

package.json, src/documentation/markdown/GettingStarted/Changelog.md
Adds ^ to the react version in dependencies to allow minor versions of React 16
In Analyze we're hoping to update our version of react to 16.9 but since UI had 16.8.6 some of our components were breaking
=> accept minor versions of react 16

src/components/Text/Text.jsx
Add 'as' as a prop to the Text component props table to explain how we can use this built in styled components feature to extend the text to be more semantic inside our apps
*Similar to Sol's recent documentation change, I suggest that we don't bump the version just for this change*
=> add as prop to Text component documentation

package-lock.json, scripts/generateComponentData.js, src/components/AppShell/AppShell.jsx, src/components/Button/Button.jsx, src/components/Modal/Modal.jsx, src/components/util/deprecated-warning.js, src/documentation/markdown/GettingStarted/Changelog.md
Adds a generic [hook for printing deprecation warnings](https://github.com/bufferapp/ui/pull/254/files#diff-ee43c5fe5a2700cb079d3b8bd55d9b0fa35d2924e98e38e588f44d9d925ba34f) (dev only) and uses it for marking `AppShell` and others as deprecated.
=> Deprecation notice for AppShell

src/documentation/markdown/GettingStarted/CHANGELOG.md
Adds details for 5.52.0 in the changelog.
=> Update Changelog with 5.52.0 details

package-lock.json, src/components/Avatar/Avatar.jsx, src/components/Modal/Modal.jsx, src/components/Modal/__snapshots__/Modal.spec.jsx.snap, src/documentation/examples/Avatar/Size/Large.jsx, src/documentation/examples/Avatar/Size/Medium.jsx, src/documentation/examples/Avatar/Size/Small.jsx, src/documentation/examples/Avatar/Type/AvatarSocial.jsx, src/documentation/examples/Modal/focus_reset.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Add Shopify as an option for the Avatar component
With the work in OneBuffer, we are currently working in SharedChannels, and there is an option to connect Shopify, but the icon is not showing up.
=> Add Shopify option in Avatar component enum

src/components/DropdownMenu/ButtonItem/ButtonItem.jsx, src/components/DropdownMenu/style.js, src/documentation/examples/DropdownMenu/DropdownMenu.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Add a new prop "disabled" to set a menu item as disabled within the Dropdown Menu component.
With the work on task CORE-1444, we need to have support for disabled menu options in the Dropdown menu component.
=> CORE-1444 | Add disable menu option for the dropdown menu items

src/components/Carousel/Carousel.jsx, src/components/Carousel/__snapshots__/Carousel.spec.js.snap, src/documentation/examples/Carousel/Carousel-no-indicators.jsx, src/documentation/examples/Carousel/Carousel-one-direction.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
1. Adds navigation option to the right only
2. adds option to hide indicator buttons
We'll need this for the resources component in Analyze
=> extend carousel

CONTRIBUTING.md, README.md, scripts/publish.sh
This updates any references to the master branch around the repo
After we changed the main branch to main, our publish script still updates master. This will ensure it updates main
=> change master to main in references

src/documentation/markdown/GettingStarted/CHANGELOG.md
the changelog fell behind with my last publish, keeping it nicely up to date :)
=> fix changelog

src/components/Button/style.js
Fix the issue #270 Button looks cut on the left side when is disabled
The `border-radius`  property should be added to the `<button>` element, inside `Button Component`.
On the left side of disabled button, the button is cut, it's look like a visual error.
It fixes an open issue: [issue-270](https://github.com/bufferapp/ui/issues/270)
=> fix: issue-270: Button looks cut on the left side when is disabled

package-lock.json, src/components/SimpleModal/SimpleModal.jsx, src/components/SimpleModal/SimpleModal.spec.js, src/components/SimpleModal/__snapshots__/SimpleModal.spec.js.snap, src/components/SimpleModal/index.js, src/components/SimpleModal/style.js, src/components/index.js, src/documentation/examples/SimpleModal/SimpleModal.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
We'll use this modal in app-shell for the plan selector. Our plan is to migrate the old modal to be an extention of this one as the old one has become a bit bloated
https://share.buffer.com/mXu1YwKo
=> create simple modal

src/components/DropdownMenu/ButtonItem/ButtonItem.jsx, src/components/DropdownMenu/DropdownMenu.jsx, src/components/DropdownMenu/PopupMenu/PopupMenu.jsx, src/components/DropdownMenu/__snapshots__/DropdownMenu.spec.js.snap, src/components/DropdownMenu/style.js, src/documentation/examples/DropdownMenu/DropdownMenu.jsx
Supports https://github.com/bufferapp/buffer-publish/pull/1716
See requirements here and discussion with @letsbleachthis: https://buffer.atlassian.net/browse/PUB-3420
=> Add `color` prop to items in DropdownMenu

package-lock.json, package.json, src/components/DropdownMenu/ButtonItem/ButtonItem.jsx, src/components/DropdownMenu/DropdownMenu.jsx, src/components/DropdownMenu/PopupMenu/PopupMenu.jsx, src/components/DropdownMenu/__snapshots__/DropdownMenu.spec.js.snap, src/components/DropdownMenu/style.js, src/components/style/colors.js, src/documentation/examples/DropdownMenu/DropdownMenu.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Changed the `color` prop to a `colors` prop on `items` passed into the `DropDownMenu` component. 
⚠️  This would be a 'breaking change' but the `color` prop was only released by me yesterday, so I'm moving this along quickly as a non-breaking change (minor semver), since nobody will use that version now.
We need to have more control over the hover styles for buttons in the menu, to support proper hover styles on menu in AppShell. (See GIF below.)
=> Add menu item color options

src/components/Input/style.js, src/components/SidebarListItem/SidebarListItem.jsx, src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap, src/components/TextArea/style.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
- Add `className` to `<SidebarListItem>`
- Adjust `border-color` and `placeholder` color in both inputs and textareas, to improve consistency and accessibility.
https://github.com/bufferapp/ui/issues/256
=> Fix input and textarea style inconsistencies

src/components/SimpleModal/SimpleModal.jsx
To vertically center the simple modal
This will allow us to better use modals on screens with small vertical resolution.
=> vertically center simple modal

src/components/Icon/Icon.jsx, src/documentation/examples/Icon/Add.jsx
Add title to svg icons for accessibility.
When working with a standalone svg icon, meaningful (and not just decorative), I realized we are missing the title here.
=> Add title to svg icons for accessibility

src/components/Button/Button.jsx, src/components/Select/SelectItem/style.js
Adjust Select component: 
- remove svg styles on hover
**Bonus:** Add props to Button, so we can use attributes like `tabIndex` and `data-testid` without having to keep adding them one by one here.
When hovering on a select option, all the svg inside it would change color. I couldn't find one single situation where it would be beneficial and was being used, so I chose to remove it. 
Also, for the calendar we have to use multiple attributes in buttons that we didn't explicitly expose, like `tabIndex` and `data-testid`.
https://buffer.atlassian.net/browse/PUB-3663
**Before:**
**After:**
=> [PUB-3663] Adjust Select component

src/components/Tag/Tag.jsx, src/components/Tag/Tag.spec.js, src/components/Tag/__snapshots__/Tag.spec.js.snap, src/components/Tag/index.js, src/components/Tag/style.js, src/documentation/examples/Tag/BasicTag.jsx, src/documentation/examples/Tag/CountTag.jsx, src/documentation/examples/Tag/IconTag.jsx, src/documentation/examples/Tag/TextTag.jsx
Adding a new Tag component. This basic component has been extracted from the shared-component `NavTag` in Publish
The motivation behind this PR is to have a Tag component that will be used in a `DropdownMenu` component for the Canva integration.
=> Add new Tag component

package-lock.json, src/components/SimpleModal/SimpleModal.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
When a modal opens, we should focus the modal on mount so that if a user wants to use their keyboard to tab through it, they have access to the modal right away
before: https://share.buffer.com/7Kuo77zm
now: https://share.buffer.com/04u277do
=> focuses Simple Modal on mount

src/components/DropdownMenu/style.js, src/components/style/colors.js, src/documentation/examples/DropdownMenu/DropdownMenu.jsx
CSS fixes for Dropdown Menu
Removing overriding styles for Dropdown menu items.
When adding more elements to the title of a menu item, like for example: `<span>Canva<Tag />New</tag>`, as you hover the menu item, the Tag changes its color because of a CSS class in the Dropdown menu component.
The CSS rule is very broad and takes whatever element. My assumption is that is not necessary. However, I probably don't have enough context to make this decision.
This PR also adds a new menu item (with an example of Canva icon) as a new possible combination. It also adds new colors for [Canva](https://www.canva.com).
=> fix: hover rules for Dropdown Item and new example

package-lock.json, package.json
To prevent colliding styles between micro frontends, let's make sure our generated class names are using the component's `displayName`. That'll eliminate any chance of two components ending up with the same class name because they're coming from different apps.
We've had one situation coming in from the Navigator and Start Pages last week.
- Slack conversation ([link](https://buffer.slack.com/archives/C0YS0TW5P/p1631752164345900)).
- PR fix on Navigator repo ([link](https://github.com/bufferapp/app-shell/pull/114)).
Today, we've had a similar situation between the Navigator and Start Pages, but in this case, it comes not from a style defined in the Navigator directly, but rather from this library.
- Slack conversation ([link](https://buffer.slack.com/archives/C0YS0TW5P/p1632268131438700)). …
=> Compile styles with displayNames

src/components/AnimationWrapper/AnimationWrapper.jsx, src/components/AnimationWrapper/__snapshots__/AnimationWrapper.spec.js.snap, src/documentation/examples/SimpleModal/SimpleModal.jsx
This fixes a bug reported in the app shell, were the `AnimationWrapper`, was interrupting and restarting the staging animation.
To prevent the staging animation from flashing because of a rerender during the transition.
[PUB-3836](https://buffer.atlassian.net/browse/PUB-3836)
=> [PUB-3836] prevent AnimationWrapper from re-rendering during staging animations

config/webpack.config.prod.js
The `SC_ATTR` helps us create a namespaced version of our styles by creating an attribute on the `<style>` tag with that value.
Having a slash in there is invalid HTML I guess, and the bundle tries to perform something like: `document.querySelectorAll('style[bufferapp/ui-styles][data-styled-version="5.1.1"]')`, which breaks. Changing it to something else (like `buffer-ui-styles`) makes it work again ✨ 
@gmzjuliana , this seems to make the `SC_ATTR` work for the docs site too, so maybe we need to keep digging to see why it's not working on the other apps! 🕵️
=> Fix docs in production by changing the formatting of the SC_ATTR

package.json, src/documentation/markdown/GettingStarted/CHANGELOG.md
changing namespacing based on this conversation https://github.com/bufferapp/ui/pull/334#pullrequestreview-770444452
=> use a hyphen instead of a forward slash in namespacing

CONTRIBUTING.md, package.json
I tried to fix it programmatically but was unable to do so, so I figured out we can just apply `eslint src/components/Icon/Icons/** --fix` as the additional step after the script. Simple and it does the trick.
There was issue with icons generation after recent migration from npm to yarn
=> Fixing gen:icons script

scripts/betaPublish.js, scripts/publish.sh, src/documentation/markdown/GettingStarted/CHANGELOG.md
When we switched to yarn, we broke the publishing scripts (yarn publishes a little differently than npm). This fixes that so anyone can publish
=> fix publishing scripts

CONTRIBUTING.md
adding 'run' to the publish command in the readme :)
=> fix publishing instructions

src/documentation/markdown/GettingStarted/CHANGELOG.md
Forgot to update the change log with changes done in #348
=> Update change log with latest changes

src/components/NonDismissibleModal/NonDismissibleModal.jsx, src/components/NonDismissibleModal/NonDismissibleModal.spec.jsx, src/components/NonDismissibleModal/__snapshots__/NonDismissibleModal.spec.jsx.snap, src/components/NonDismissibleModal/index.js, src/components/SimpleModal/SimpleModal.jsx, src/components/SimpleModal/style.js, src/documentation/examples/NonDismissibleModal/NonDismissibleModal.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
This adds a `NonDismissibleModal` component.
This new component reuses the styling of the `SimpleModal` but removes the user dismissible logic.
This is needed for the Paywall modals
[WEBAPP-384](https://buffer.atlassian.net/browse/WEBAPP-384)
=> add NonDismissibleModal

src/components/SimpleModal/SimpleModal.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
SimpleModals should be dismissed by pressing `<ESC>`
=> Allow dismissing SimpleModal when pressing ESC

src/components/Avatar/Avatar.jsx, src/components/SidebarListItem/SidebarListItem.jsx, src/components/style/colors.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
Adding TikTok icon, to be used with new channel in Publish
=> SidebarListIcon: adding tiktok

src/components/Tooltip/Tooltip.jsx, src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
Remove extra div from tooltip that was causing some issues with style propagation [ref.](https://buffer.slack.com/archives/C151RRDL1/p1652813987964289?thread_ts=1652792652.660759&cid=C151RRDL1)
=> remove extra div from tooltip

src/components/Button/style.js
[WEBAPP-528](https://buffer.atlassian.net/browse/WEBAPP-528): Set gray color for secondary button divider line and light blue for primary.
Just a small styling change to make things look consistent
**Before:**
**After:**
=> [WEBAPP-528] Set gray color for secondary button divider line

src/components/Avatar/Avatar.jsx, src/components/Avatar/__snapshots__/Avatar.spec.js.snap, src/components/Avatar/style.js, src/components/SidebarListItem/__snapshots__/SidebarListItem.spec.js.snap, src/documentation/examples/Avatar/Type/AvatarSocial.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Adds the start page icon in Avatar since we're working on making Start Page a buffer channel
https://buffer.atlassian.net/browse/SP-655
=> adds startPage as network option in Avatar

src/components/Avatar/Avatar.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
I forgot to change the import to the right one in previous update, it's a fix for that
=> Fix: Gmb icon to Gbp icon change in Avatar.jsx

package.json, src/components/DropdownMenu/PopupMenu/style.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
Remove the scrollbar shown by default in the Dropdown menu. 
If we remove this CSS value, it'll only be shown if needed and not always like it's the case now.
Compare: 
With:
=> Remove scrollbar from Dropdown component by default

src/components/Select/SelectItem/SelectItem.jsx, src/components/Select/SelectItem/style.js
=> CSS Fixes for SelectedItem with IconEnd

src/components/Avatar/Avatar.jsx, src/components/SidebarListItem/SidebarListItem.jsx, src/components/style/colors.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
changing the color for SP avatar and fixing some proptypes for work in publish 😊 
https://buffer.atlassian.net/browse/SP-764
=> change SP avatar

src/components/Button/Button.jsx, src/components/Button/style.js, src/components/Select/Select.jsx, src/components/Select/__snapshots__/Select.spec.js.snap, src/documentation/examples/Select/SelectWithItemTextToLeft.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Allow text alignment to the left on the Select component.
Select components are aligned centered by default. This change is in the case we have a bigger selector and want the text to be aligned to the left.
This is related to multiple UX improvements on this task: https://buffer.atlassian.net/browse/EPD-236
=> Allow text alignment to left on Select

src/components/Icon/Icon.jsx, src/components/Icon/style.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
Add smedium size to icon options, to have a 12px icon
Part of UX improvements in preparation for Twitter Threads work: https://buffer.atlassian.net/browse/EPD-269
=> [EPD-269] Add smedium size to icon options

src/components/NavBar/NavBarMenu/style.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
=> fix NavBarChavron alignment

package.json, src/components/style/colors.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
=> Add new color for Youtube

package.json, src/components/Avatar/Avatar.jsx, src/components/style/colors.js
Support mastodon as a social type in `Avatar`
Add new mastodon color: `#595aff`
https://buffer.atlassian.net/browse/EPD-579
=> [EPD-579] Support Mastodon in Avatar

.travis.yml, package.json, src/components/style/colors.js, src/documentation/markdown/GettingStarted/CHANGELOG.md
=> [EPD-579] Update Mastodon color

package.json, src/documentation/markdown/GettingStarted/CHANGELOG.md, types/index.d.ts
Add default type definitions to solve errors in buffer-mono - Ideally, this repo should become a TS repo and the TS cli should generate them for us.
=> Add default type definitions

types/index.d.ts
=> Add missing module

package.json, src/components/Avatar/Avatar.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
Fix mastodon warning for Avatar
```
bugsnag.js:2672 Warning: Failed prop type: Invalid prop `network` of value `mastodon` supplied to `Avatar`, expected one of ["facebook","twitter","instagram","linkedin","google","pinterest","shopify","tiktok","startPage","googlebusiness"].
```
=> Fix mastodon warning for Avatar

package.json, src/components/Tooltip/style.js, yarn.lock
The current version of reach/tooltip has a peer dependency for react@^16.8.0 which cause an unmeet peer error in buffer-mono
This PR updates reach/tooltip to version 0.18.0 to use `bufferapp/ui` in the buffer-mono with react >= 17 and solve the unmeet peer dependency.
@esclapes, in preparation for moving this repo over to buffer-mono in Q2, the frontend WG could help by upgrading react to v17 at least.
=> Update reach/tooltip to latest

package.json, src/components/Tooltip/style.js, yarn.lock
=> Revert "Update reach/tooltip to latest"

src/components/Avatar/Avatar.jsx, src/documentation/markdown/GettingStarted/CHANGELOG.md
=> Adding youtube icon to Avatar component

package.json, src/components/Avatar/Avatar.tsx, src/components/Avatar/style.ts, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/Icon/utils/createIconComponent.ts, src/components/Search/Search.test.tsx, src/components/Select/Select.test.tsx, src/components/Tooltip/style.ts, yarn.lock
=> Use React v17

.eslintignore, .gitignore, .prettierignore, package.json, scripts/copyBuildFiles.js, scripts/publish.sh, scripts/publishBeta.sh, scripts/sync.sh, src/documentation/version.ts
use dist instead of lib for buffer-mono
=> use dist instead of lib for buffer-mono
